### ISSUE TITLE
Setting up a new config

### ISSUE THREAD

**Issue by Jaques08** [marlanperumal/pdf_statement_reader#28]
Can you perhaps assist me with how I go about setting up new config for different statements. I do have the example setup for ZA Absa, and would like to try it with different statements. 

Maybe a quick guide in the README to show how all the settings are setup, e.g page layout.

**Comment by marlanperumal** [comment]
Thanks for your interest and feedback. I haven't touched this repo in a while so will need to refamiliarize myself with it :)

I reckon the most useful thing would be a couple of marked-up images of a sample statement, showing exactly what each of the config parameters refers to but that'll take me a while to put together.

Can you explain what specifically, in the current description in the REAMDE of the config file you're having trouble with? Documentation's not really my strong point but I can answer your questions and then I'll happily accept pull requests with documentation updates if you're able to describe it better.

Another option is to use the actual [tabula GUI](https://tabula.technology/) to get a feel for how the areas are defined.

**Comment by marlanperumal** [comment]
So having taken a look at a couple of other statement formats (Absa Credit and Standard Bank Cheque) it's clear that the format of these can vary significantly (hence the note in the README from my past self about the list of format options likely needing to grow). I can understand now why my initial config options may not have made sense if you were looking at a statement with a completely different format.

I'll have to have a think about how to expand the option set in a more generic away. Happy to take suggestions.

**Comment by Jaques08** [comment]
Hi @marlanperumal  apologies for the late response. So just as some background I'd like to take different bank statement pdfs and convert them to csv so I can extract line by line the transactions made on that statement. 

So mostly I'm not 100% sure about the layout params, how would did you initially get them? 

Also I've played around with tabula-py after your suggestion above, would you think that's a better option perhaps? Sorry I haven't yet played around with pdf's and the tools surrounding it too much

**Comment by flywire** [comment]
> Another option is to use the actual [tabula GUI](https://tabula.technology/) to get a feel for how the areas are defined.

Hmm, I've done that and it just pulls out different areas for each page.

1. What are the coordinate units?
2. Exactly how is [tabula GUI](https://tabula.technology/) used to identify columns instead of the whole area on page with data?
