### ISSUE TITLE
Install in Python Virtual Environment

### ISSUE THREAD

**Issue by flywire** [marlanperumal/pdf_statement_reader#32]
Unreasonable to assume `psr` will run this progam. Suggest install into Python Virtual Environment.

See #36

**Comment by marlanperumal** [comment]
`psr` is the cli command exposed by this package. The user is free to install it however they choose, be it in the system python packages, a venv or, as is used in the development of this package, using pipenv

**Comment by flywire** [comment]
Better still, use https://pipenv.pypa.io

Also see #37
