### ISSUE TITLE
Script name clash on Windows

### ISSUE THREAD

**Issue by HyTurtle** [marlanperumal/pdf_statement_reader#37]
https://github.com/marlanperumal/pdf_statement_reader/blob/e1d6ee13226e0b7688f155dcd25c4e4908a4255b/setup.py#L37

On Windows the name is a clash with Steps Recorder; which being in System32 take precedence.

**Comment by marlanperumal** [comment]
Should be able to add a second command alias in the `console_scripts` list. Are you able to try it out and submit a pull request?

**Comment by HyTurtle** [comment]
Added a platform check and conditional on the singhle entry, would it be better to just add as a secondary?

**Comment by marlanperumal** [comment]
I think a secondary would be a bit cleaner. A complicated f-string in the setup.py is a bit of a code smell.

**Comment by HyTurtle** [comment]
I was testing in a venv - and the steps recorder still took precedence.
Committed with the secondary; averse to just the platform check so there isn't a dupe?

**Comment by flywire** [comment]
@HyTurtle Steps recorder must install first in your path. Can you test with [pipenv](https://github.com/marlanperumal/pdf_statement_reader/issues/32#issuecomment-861032503)?

**Comment by HyTurtle** [comment]
Within pipenv seems fine; a tad odd since just virtualenv (which pipenv itself uses) was defaulting to the system32 despite the venv Script path being first in the %path%. I was using PyCharm for the latter perhaps the _issue_ lies there
